extends: '@ficsit/code-style'

ignorePatterns:
  - 'pipeline/headers-to-interfaces/grammar/*'
  - 'pipeline/ue4pak-cleaner/fixtures/*'

overrides:
  - files: 'pipeline/headers-to-interfaces/**/*.{ts,tsx}'
    parserOptions:
      project: 'pipeline/headers-to-interfaces/tsconfig.json'
  - files: 'pipeline/ue4pak-cleaner/**/*.{ts,tsx}'
    parserOptions:
      project: 'pipeline/ue4pak-cleaner/tsconfig.json'
  - files: 'pipeline/headers-to-interfaces/emit/native/**/*.{ts,tsx}'
    rules:
      '@typescript-eslint/no-empty-interface': 'off'
