extends: '@ficsit/code-style'

ignorePatterns:
  - 'pipeline/headers-to-interfaces/generated/'
  - 'pipeline/ue4pak-cleaner/fixtures/'

overrides:
  - files: 'packages/pak-parser/**/*.{ts,tsx}'
    parserOptions:
      project: 'packages/pak-parser/tsconfig.json'

  - files: 'packages/pipeline/**/*.{ts,tsx}'
    parserOptions:
      project: 'packages/pipeline/tsconfig.json'

  - files: 'pipeline/extract-source/**/*.{ts,tsx}'
    parserOptions:
      project: 'pipeline/extract-source/tsconfig.json'

  - files: 'pipeline/headers-to-interfaces/**/*.{ts,tsx}'
    parserOptions:
      project: 'pipeline/headers-to-interfaces/tsconfig.json'
    rules:
      'import/namespace': 'off'

  - files: 'pipeline/headers-to-interfaces/emit/native/**/*.{ts,tsx}'
    rules:
      '@typescript-eslint/no-empty-interface': 'off'

  - files: 'pipeline/ue4pak-cleaner/**/*.{ts,tsx}'
    parserOptions:
      project: 'pipeline/ue4pak-cleaner/tsconfig.json'
    rules:
      '@typescript-eslint/camelcase': 'off'
