name: 'Updated: source-data'

on: [push, repository_dispatch]

jobs:
  setup:
    if: github.event_name == 'push' || github.event.action == 'source-data-updated'
    runs-on: ubuntu-latest
    steps:
      - name: Determine source ref and game branch
        run: |
          REF="${{ github.event.client_payload.ref }}"
          if [[ "${REF}" != "" ]]; then
            echo "::set-env name=GAME_BRANCH::${REF#refs/head/}" >> ./env-vars
            echo "::set-env name=_SOURCE_REF::${{ github.event.client_payload.sha }}"
          else
            echo "::set-env name=GAME_BRANCH::master" >> ./env-vars
            echo "::set-env name=_SOURCE_REF::master"
          fi

      - name: Checkout source-data
        uses: actions/checkout@v2
        with:
          path: source-data
          repository: ficsit/source-data
          ref: ${{ env._SOURCE_REF }}

      - name: Set pipeline refs
        working-directory: ./source-data
        run: |
          SOURCE_SHA=$(git rev-parse HEAD)

          echo "::set-env name=LANDING_BRANCH::working/${SOURCE_SHA}/${{ github.sha }}" >> ../env-vars
          echo "::set-env name=ENGINEERING_SHA::${{ github.sha }}" >> ../env-vars
          echo "::set-env name=SOURCE_SHA::${SOURCE_SHA}" >> ../env-vars

          cat ../env-vars

      - name: Checkout data-landing
        uses: actions/checkout@v2
        with:
          path: data-landing
          repository: ficsit/data-landing
          ref: ${{ env.GAME_BRANCH }}
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Create working branch
        working-directory: ./data-landing
        run: git checkout -b ${LANDING_BRANCH}

      - name: Push working branch
        working-directory: ./data-landing
        run: git push origin ${LANDING_BRANCH}

      - name: Set game metadata
        working-directory: ./source-data
        run: |
          echo "::set-env name=GAME_VERSION::$(jq -r .version.public metadata.json)" >> ../env-vars
          echo "::set-env name=GAME_BUILD::$(jq -r .version.build metadata.json)" >> ../env-vars

      - uses: actions/upload-artifact@v1
        with:
          name: env-vars
          path: env-vars

  headers-to-interfaces:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: env-vars
      - name: Load configuration
        run: cat env-vars/env-vars

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Checkout data-engineering
        uses: actions/checkout@v2
        with:
          path: data-engineering

      - name: Checkout source-data
        uses: actions/checkout@v2
        with:
          path: source-data
          repository: ficsit/source-data
          ref: ${{ env.SOURCE_SHA }}

      - name: Checkout data-landing
        uses: actions/checkout@v2
        with:
          path: data-landing
          repository: ficsit/data-landing
          ref: ${{ env.LANDING_BRANCH }}
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Install dependencies
        working-directory: ./data-engineering
        run: yarn install --frozen-lockfile

      - name: yarn headers-to-interfaces
        working-directory: ./data-engineering
        run: |
          yarn headers-to-interfaces \
            "${GITHUB_WORKSPACE}"/source-data/headers \
            "${GITHUB_WORKSPACE}"/data-landing/interface

      - name: Push to data-landing
        working-directory: ./data-landing
        run: |
          git config --global user.email "ficsit-bot@nevir.net"
          git config --global user.name "Ficsit Bot"
          git add .
          git commit --allow-empty -m "headers-to-interfaces"
          git push

  merge:
    needs:
      - headers-to-interfaces
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: env-vars
      - name: Load configuration
        run: cat env-vars/env-vars

      - name: Checkout data-landing
        uses: actions/checkout@v2
        with:
          repository: ficsit/data-landing
          ref: ${{ env.GAME_BRANCH }}
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Merge
        run: |
          git config --global user.email "ficsit-bot@nevir.net"
          git config --global user.name "Ficsit Bot"
          git fetch origin ${LANDING_BRANCH}
          git merge --squash origin/${LANDING_BRANCH}
          git commit --allow-empty -m "v${GAME_VERSION} (CL ${GAME_BUILD}) (ficsit/source-data@${SOURCE_SHA} via ficsit/data-engineering@${ENGINEERING_SHA})"
          git tag -f v${GAME_VERSION}
          git push --all

      - name: Cleanup
        run: |
          git push origin --delete ${LANDING_BRANCH}
