name: 'Updated: source-data'

on: repository_dispatch

jobs:
  setup:
    if: github.event.action == 'source-data-updated'
    runs-on: ubuntu-latest
    steps:
      - name: Set Git Author
        run: |
          git config --global user.email "ficsit-bot@nevir.net"
          git config --global user.name "Ficsit Bot"

      - name: Checkout data-landing
        uses: actions/checkout@v2
        with:
          repository: ficsit/data-landing
          ref: ${{ github.event.client_payload.ref }}
          token: ${{ secrets.PUSH_TOKEN }}

      - run: cat ~/.gitconfig

      - name: Create working branch
        run: git checkout -b working/${{ github.event.client_payload.sha }}/${{ github.sha }}

      - name: Push working branch
        run: git push origin working/${{ github.event.client_payload.sha }}/${{ github.sha }}

  headers-to-interfaces:
    if: github.event.action == 'source-data-updated'
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data-engineering
        uses: actions/checkout@v2
        with:
          path: data-engineering

      - name: Checkout source-data
        uses: actions/checkout@v2
        with:
          path: source-data
          repository: ficsit/source-data
          ref: ${{ github.event.client_payload.sha }}

      - name: Checkout data-landing
        uses: actions/checkout@v2
        with:
          path: source-data
          repository: ficsit/data-landing
          ref: working/${{ github.event.client_payload.sha }}/${{ github.sha }}
